version: '3.9'

services:
  pharmacy:
    image: marijakljestan/pharmacy
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    restart: on-failure
    networks:
      - application
      - database
    depends_on:
      - database
  database:
    image: postgres:14.1
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: drugstore123
      POSTGRES_USER: postgres
      POSTGRES_DB: pharmacy
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: scripts/init.sql
        target: docker-entrypoint-initdb.d
    ports:
      - 5555:5432

volumes:
  database-data:
    name: pharmacy-database

networks:
  application:
    name: application
    driver: bridge
  database:
    name: database
    driver: bridge